### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pattywap** [trentrand/cypress-utils#17]
When running, npx cypress-utils --help, i get this.

`/home/user/node_modules/cypress-utils/index.js:185
argv.testFiles = argv.testFiles ?? cypressConfig.testFiles ?? '**/*.*';
                                 ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
`

**Comment by trentrand** [comment]
Your installation of NodeJS doesn't seem to recognize the [nullish coalescing operator (??)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator). You'll need to upgrade NodeJS to version 14.0.0 or newer.

I'll update the `package.json` to specify this requirement.

**Comment by trentrand** [comment]
This has been fixed in version v2.1.1.

Be sure to use Node v14.0.0 or newer!

Thank you for reporting the issue!
